export default {
  "section_one_header": "The game-changing event for innovative and sustainable fashion.",
  "section_one_body_text": "Fashion is changing for the better. Be a part of the solution in a two-day event packed with innovative ideas, practical solutions and new connections.",
  "section_one_image": {
    "id": 95,
    "alt": "",
    "title": "women_standing_outside",
    "caption": "",
    "description": "",
    "mime_type": "image\/jpeg",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/women_standing_outside-1.jpg",
    "width": 2000,
    "height": 1333,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/women_standing_outside-1-150x150.jpg",
      "thumbnail-width": 150,
      "thumbnail-height": 150,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/women_standing_outside-1-300x200.jpg",
      "medium-width": 300,
      "medium-height": 200,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/women_standing_outside-1-768x512.jpg",
      "medium_large-width": 525,
      "medium_large-height": 350,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/women_standing_outside-1-1024x682.jpg",
      "large-width": 525,
      "large-height": 350,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/women_standing_outside-1-2000x1200.jpg",
      "twentyseventeen-featured-image-width": 2000,
      "twentyseventeen-featured-image-height": 1200,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/women_standing_outside-1-100x100.jpg",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 100
    }
  },
  "section_two_header": "Experience REMODE",
  "section_two_body_text": "Content and experiences at REMODE are built on four pillars. Within each pillar, participants will explore the present issues in the industry and shape the future of fashion with two days of conferences, workshops, exhibits and networking events. This 360 approach allows brands to break the silos, connect the dots and truly make a difference within their organizations.",
  "rethink_tile_text": "Consumer trends for the future and innovations in product and materials.",
  "rethink_tile_background_image": {
    "id": 91,
    "alt": "",
    "title": "rethink_block",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/rethink_block-1.png",
    "width": 660,
    "height": 760,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/rethink_block-1-150x150.png",
      "thumbnail-width": 150,
      "thumbnail-height": 150,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/rethink_block-1-261x300.png",
      "medium-width": 261,
      "medium-height": 300,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/rethink_block-1.png",
      "medium_large-width": 525,
      "medium_large-height": 605,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/rethink_block-1.png",
      "large-width": 525,
      "large-height": 605,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/rethink_block-1.png",
      "twentyseventeen-featured-image-width": 660,
      "twentyseventeen-featured-image-height": 760,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/rethink_block-1-100x100.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 100
    }
  },
  "remake_tile_text": "Ideas and solutions for design, production, wearables, and sustainability.",
  "remake_tile_background_image": {
    "id": 89,
    "alt": "",
    "title": "remake_block",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remake_block-1.png",
    "width": 660,
    "height": 760,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remake_block-1-150x150.png",
      "thumbnail-width": 150,
      "thumbnail-height": 150,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remake_block-1-261x300.png",
      "medium-width": 261,
      "medium-height": 300,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remake_block-1.png",
      "medium_large-width": 525,
      "medium_large-height": 605,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remake_block-1.png",
      "large-width": 525,
      "large-height": 605,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remake_block-1.png",
      "twentyseventeen-featured-image-width": 660,
      "twentyseventeen-featured-image-height": 760,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remake_block-1-100x100.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 100
    }
  },
  "remarket_tile_text": "Marketing and sales strategies for omnichannel success, including technological innovations and best practices in storytelling.",
  "remarket_tile_background_image": {
    "id": 90,
    "alt": "",
    "title": "remarket_block",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remarket_block-1.png",
    "width": 660,
    "height": 760,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remarket_block-1-150x150.png",
      "thumbnail-width": 150,
      "thumbnail-height": 150,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remarket_block-1-261x300.png",
      "medium-width": 261,
      "medium-height": 300,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remarket_block-1.png",
      "medium_large-width": 525,
      "medium_large-height": 605,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remarket_block-1.png",
      "large-width": 525,
      "large-height": 605,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remarket_block-1.png",
      "twentyseventeen-featured-image-width": 660,
      "twentyseventeen-featured-image-height": 760,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/remarket_block-1-100x100.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 100
    }
  },
  "reinvest_tile_text": "Innovative ways to finance and maintain a sustainable brand.",
  "reinvest_tile_background_image": {
    "id": 88,
    "alt": "",
    "title": "reinvest_block",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/reinvest_block-1.png",
    "width": 660,
    "height": 760,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/reinvest_block-1-150x150.png",
      "thumbnail-width": 150,
      "thumbnail-height": 150,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/reinvest_block-1-261x300.png",
      "medium-width": 261,
      "medium-height": 300,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/reinvest_block-1.png",
      "medium_large-width": 525,
      "medium_large-height": 605,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/reinvest_block-1.png",
      "large-width": 525,
      "large-height": 605,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/reinvest_block-1.png",
      "twentyseventeen-featured-image-width": 660,
      "twentyseventeen-featured-image-height": 760,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/reinvest_block-1-100x100.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 100
    }
  },
  "attendees_block_header": "Attendees",
  "attendees_block_body_text": "If you are a fashion brand, you will hear the best ideas, meet the right people and find the resources to design and execute an actionable growth plan. You will connect to the network that will make you succeed in a fast-changing market!",
  "attendees_block_image": {
    "id": 93,
    "alt": "",
    "title": "attendees_looking_at_phone",
    "caption": "",
    "description": "",
    "mime_type": "image\/jpeg",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/attendees_looking_at_phone-1.jpg",
    "width": 2000,
    "height": 1333,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/attendees_looking_at_phone-1-150x150.jpg",
      "thumbnail-width": 150,
      "thumbnail-height": 150,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/attendees_looking_at_phone-1-300x200.jpg",
      "medium-width": 300,
      "medium-height": 200,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/attendees_looking_at_phone-1-768x512.jpg",
      "medium_large-width": 525,
      "medium_large-height": 350,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/attendees_looking_at_phone-1-1024x682.jpg",
      "large-width": 525,
      "large-height": 350,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/attendees_looking_at_phone-1-2000x1200.jpg",
      "twentyseventeen-featured-image-width": 2000,
      "twentyseventeen-featured-image-height": 1200,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/attendees_looking_at_phone-1-100x100.jpg",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 100
    }
  },
  "exhibitors_and_sponsors_block_header": "Exhibitors and Sponsors",
  "exhibitors_and_sponsors_block_body_text": "If you are a fashion tech company, an innovative or sustainable raw material supplier, a tech, retail or services company focused on fashion, REMODE is a unique opportunity to show who you are, share your story, build your leadership, generate leads and connect with the fashion community.",
  "exhibitors_and_sponsors_block_image": {
    "id": 94,
    "alt": "",
    "title": "exhibitor_working",
    "caption": "",
    "description": "",
    "mime_type": "image\/jpeg",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/exhibitor_working-1.jpg",
    "width": 2000,
    "height": 1300,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/exhibitor_working-1-150x150.jpg",
      "thumbnail-width": 150,
      "thumbnail-height": 150,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/exhibitor_working-1-300x195.jpg",
      "medium-width": 300,
      "medium-height": 195,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/exhibitor_working-1-768x499.jpg",
      "medium_large-width": 525,
      "medium_large-height": 341,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/exhibitor_working-1-1024x666.jpg",
      "large-width": 525,
      "large-height": 341,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/exhibitor_working-1-2000x1200.jpg",
      "twentyseventeen-featured-image-width": 2000,
      "twentyseventeen-featured-image-height": 1200,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/exhibitor_working-1-100x100.jpg",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 100
    }
  },
  "forms_section_header": "Stay Tuned for Updates",
  "sponsor_image_1": {
    "id": 101,
    "alt": "",
    "title": "CFDA",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/CFDA.png",
    "width": 160,
    "height": 62,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/CFDA-150x62.png",
      "thumbnail-width": 150,
      "thumbnail-height": 62,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/CFDA.png",
      "medium-width": 160,
      "medium-height": 62,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/CFDA.png",
      "medium_large-width": 160,
      "medium_large-height": 62,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/CFDA.png",
      "large-width": 160,
      "large-height": 62,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/CFDA.png",
      "twentyseventeen-featured-image-width": 160,
      "twentyseventeen-featured-image-height": 62,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/CFDA-100x62.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 62
    }
  },
  "sponsor_image_2": {
    "id": 105,
    "alt": "",
    "title": "WWD",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/WWD.png",
    "width": 160,
    "height": 62,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/WWD-150x62.png",
      "thumbnail-width": 150,
      "thumbnail-height": 62,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/WWD.png",
      "medium-width": 160,
      "medium-height": 62,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/WWD.png",
      "medium_large-width": 160,
      "medium_large-height": 62,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/WWD.png",
      "large-width": 160,
      "large-height": 62,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/WWD.png",
      "twentyseventeen-featured-image-width": 160,
      "twentyseventeen-featured-image-height": 62,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/WWD-100x62.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 62
    }
  },
  "sponsor_image_3": {
    "id": 102,
    "alt": "",
    "title": "LeSouk",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/LeSouk.png",
    "width": 190,
    "height": 62,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/LeSouk-150x62.png",
      "thumbnail-width": 150,
      "thumbnail-height": 62,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/LeSouk.png",
      "medium-width": 190,
      "medium-height": 62,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/LeSouk.png",
      "medium_large-width": 190,
      "medium_large-height": 62,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/LeSouk.png",
      "large-width": 190,
      "large-height": 62,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/LeSouk.png",
      "twentyseventeen-featured-image-width": 190,
      "twentyseventeen-featured-image-height": 62,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/LeSouk-100x62.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 62
    }
  },
  "sponsor_image_4": {
    "id": 103,
    "alt": "",
    "title": "NYFTL",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/NYFTL.png",
    "width": 160,
    "height": 62,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/NYFTL-150x62.png",
      "thumbnail-width": 150,
      "thumbnail-height": 62,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/NYFTL.png",
      "medium-width": 160,
      "medium-height": 62,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/NYFTL.png",
      "medium_large-width": 160,
      "medium_large-height": 62,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/NYFTL.png",
      "large-width": 160,
      "large-height": 62,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/NYFTL.png",
      "twentyseventeen-featured-image-width": 160,
      "twentyseventeen-featured-image-height": 62,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/NYFTL-100x62.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 62
    }
  },
  "powered_by_image": {
    "id": 104,
    "alt": "",
    "title": "UBM",
    "caption": "",
    "description": "",
    "mime_type": "image\/png",
    "url": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/UBM.png",
    "width": 280,
    "height": 62,
    "sizes": {
      "thumbnail": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/UBM-150x62.png",
      "thumbnail-width": 150,
      "thumbnail-height": 62,
      "medium": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/UBM.png",
      "medium-width": 280,
      "medium-height": 62,
      "medium_large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/UBM.png",
      "medium_large-width": 280,
      "medium_large-height": 62,
      "large": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/UBM.png",
      "large-width": 280,
      "large-height": 62,
      "twentyseventeen-featured-image": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/UBM.png",
      "twentyseventeen-featured-image-width": 280,
      "twentyseventeen-featured-image-height": 62,
      "twentyseventeen-thumbnail-avatar": "https:\/\/remode.wpengine.com\/wp-content\/uploads\/2018\/03\/UBM-100x62.png",
      "twentyseventeen-thumbnail-avatar-width": 100,
      "twentyseventeen-thumbnail-avatar-height": 62
    }
  }
}
